USE mydb;

CREATE TABLE STUDENT
(SID INT(4), SNAME VARCHAR(15));

INSERT INTO STUDENT VALUES (101, 'DAVID');
INSERT INTO STUDENT VALUES (102, 'SMITH');
INSERT INTO STUDENT VALUES (103, 'SCOTT');

COMMIT;

SELECT * FROM STUDENT;

ALTER TABLE STUDENT ADD(GRADE VARCHAR(2));
DESCRIBE STUDENT;

ALTER TABLE STUDENT DROP COLUMN GRADE;


ALTER TABLE STUDENT MODIFY COLUMN SNAME VARCHAR(20);

ALTER TABLE STUDENT RENAME COLUMN SNAME TO STUNAME;
