use hr;

select * from employees;

SELECT * FROM EMPLOYEES WHERE YEAR(HIRE_DATE)="1987";

SELECT * FROM EMPLOYEES WHERE MONTH(HIRE_DATE)="6";

SELECT * FROM EMPLOYEES WHERE MONTHNAME(HIRE_DATE)="JUNE";