-- Display employees whose salary is less than the of Ellen's salary

SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'ELLEN'; -- 11000.00

SELECT SALARY FROM EMPLOYEES WHERE SALARY < 11000.00; 

SELECT SALARY FROM EMPLOYEES WHERE SALARY < (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'ELLEN'); -- how to use two query in one. (Inner query and outer query)

-- 2nd max salary from employee & 3rd max

SELECT SALARY FROM EMPLOYEES;

SELECT MAX(SALARY) FROM EMPLOYEES WHERE SALARY< 
  (SELECT MAX(SALARY) FROM EMPLOYEES WHERE SALARY < 
     (SELECT MAX(SALARY) FROM EMPLOYEES));

-- Find the salary of employees whose salary is greater than the salary of emoployee whose
-- EMPLOYEE_ID 150.

SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 150; 
SELECT SALARY FROM EMPLOYEES WHERE SALARY > 10000.00; -- ALTERNATIVE

SELECT SALARY FROM EMPLOYEES WHERE SALARY > 
(SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 150);

-- Display the employees who all are earning the highest salary.

SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

