use hr;

select department_id, sum(salary) 
from employees group by department_id;

select department_id, avg(salary) 
from employees group by department_id;

SELECT DEPARTMENT_ID, MAX(SALARY), MIN(SALARY) 
FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID, JOB_ID;

SELECT job_id, COUNT(*) FROM EMPLOYEES GROUP BY job_id HAVING COUNT(*) > 20;

SELECT DEPARTMENT_ID, SUM(SALARY) FROM employees GROUP BY DEPARTMENT_ID HAVING SUM(SALARY) > 20000;

SELECT DEPARTMENT_ID, SUM(SALARY) 
FROM EMPLOYEES 
WHERE DEPARTMENT_ID <> 50 
GROUP BY DEPARTMENT_ID 
having sum(salary) > 10000;

select * from employees order by department_id desc;

select * from employees order by salary desc;

SELECT DEPARTMENT_ID, SUM(SALARY) 
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID 
HAVING SUM(SALARY) > 20000 
ORDER BY SUM(SALARY);

SELECT DEPARTMENT_ID, SUM(SALARY) 
FROM EMPLOYEES 
WHERE DEPARTMENT_ID <> 100 
GROUP BY DEPARTMENT_ID 
HAVING SUM(SALARY)<> 20000 
ORDER BY SUM(SALARY) DESC;

