SELECT FIRST_NAME, SALARY, DEPARTMENTS.DEPARTMENT_ID FROM EMPLOYEES INNER JOIN departments
ON 
EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT FIRST_NAME, SALARY, DEPARTMENTS.DEPARTMENT_ID FROM EMPLOYEES LEFT JOIN departments
ON 
EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, DEPT.DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID 
FROM EMPLOYEES EMP INNER JOIN DEPARTMENTS DEPT ON
(EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID);

SELECT E.EMPLOYEE_ID, M.MANAGER_ID, E.FIRST_NAME, E.JOB_ID, M.FIRST_NAME FROM EMPLOYEES E,
EMPLOYEES M WHERE EMPLOYEE_ID = M.MANAGER_ID;

SELECT E.EMPLOYEE_ID, M.MANAGER_ID, E.FIRST_NAME FROM EMPLOYEES E, EMPLOYEES M
WHERE E.EMPLOYEE_ID=M.MANAGER_ID;