USE mydb;
CREATE TABLE STUDENT
(SNO INT(5),
SNAME VARCHAR(15),
MARKS INT(3));

DESCRIBE STUDENT;
  
INSERT INTO STUDENT VALUES(101,'KIRAN',80);  
INSERT INTO STUDENT(SNAME,SNO,MARKS) VALUES('RAM',102,60);
INSERT INTO STUDENT VALUES(103,'KRISHNA',NULL);
  
SELECT * FROM STUDENT;
